version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - langgraph

  langgraph:
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./agent:/app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
