[project]
name = "excel-mcp"
version = "0.1.0"
description = "MCP server for Excel file manipulation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cpca>=0.5.5",
    "dask[complete]>=2025.3.0",
    "matplotlib>=3.10.1",
    "mcp[cli]>=1.6.0",
    "modin>=0.32.0",
    "openpyxl>=3.1.2",
    "pandas>=2.2.3",
    "pyecharts>=2.0.8",
    "python-calamine>=0.3.2",
    "setuptools>=78.1.0",
    "statsmodels>=0.14.4",
]

[[project.authors]]
name = "KonghaYao"
email = "3446798488@qq.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mcp-excel = "src.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src/"]

[tool.hatch.build]
packages = ["src/"]

[[tool.uv.index]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple/"
priority = "primary"
